version: 2
deploy_expo_android: &deploy_expo_android
  working_directory: ~/circle
  docker:
    - image: circleci/node:10.4.1
  steps:
    - checkout

    - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

    - run:
        name: Installing dependencies
        command: npm install

    - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

    - run:
        name: Login into Expo
        command: npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive

    - run:
       name: Build android
       command: npx expo build:android --no-publish --non-interactive

    - run:
        name: Downloading built apk
        command: curl -o app.apk "$(expo url:apk)"

    - run:
        name: Uploading to DeployGate
        command: curl -F "token=${DEPLOY_GATE_TOKEN}" -F "file=@./app.apk" -F "message=Release 1.0.0" https://deploygate.com/api/users/${DEPLOY_GATE_USERNAME}/apps

jobs:
  deploy_expo_android_staging:
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *deploy_expo_android

  deploy_expo_android_prod:
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *deploy_expo_android

workflows:
  version: 2
  my_app:
    jobs:
      - deploy_expo_android_staging:
          filters:
            branches:
              only: development
      - deploy_expo_android_prod:
          filters:
            branches:
              only: production
